### ISSUE TITLE
Other plugin's settings get hidden

### ISSUE THREAD

**Issue by t-schroeder** [epfl-cede/moodle-mod-assign-submission-noto#2]
We have another plugin that has a setting called "apikey" and [amd/src/settings.js#L52](https://github.com/epfl-cede/moodle-mod-assign-submission-noto/blob/4e639162621d19b453fb35f19c7931d57bccb298/amd/src/settings.js#L52) hides that setting, even though it's from a different plugin.

**Comment by BenGig** [comment]
We will make the plugin fit for PHP 8.2, and add this issue to the task list.

**Comment by BenGig** [comment]
@t-schroeder it is meant to be fixed in tag v3.1.0-beta1. We don't have such a collision and cannot test, if you have an environment for testing, you're invited.
